# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{vidibus-helpers}
  s.version = "0.0.5"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Andre Pankratz"]
  s.date = %q{2011-08-18}
  s.description = %q{A collections of application helpers.}
  s.email = %q{andre@vidibus.com}
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/vidibus-helpers.rb",
    "lib/vidibus/helpers.rb",
    "lib/vidibus/helpers/extensions.rb",
    "lib/vidibus/helpers/extensions/controller.rb",
    "lib/vidibus/helpers/extensions/view.rb",
    "spec/spec_helper.rb",
    "spec/vidibus/helpers/action_view_spec.rb",
    "vidibus-helpers.gemspec"
  ]
  s.homepage = %q{http://github.com/vidibus/vidibus-helpers}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.6.2}
  s.summary = %q{Helpers for Vidibus applications.}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activesupport>, [">= 3"])
      s.add_runtime_dependency(%q<actionpack>, [">= 3"])
      s.add_development_dependency(%q<rspec>, ["~> 2"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
    else
      s.add_dependency(%q<activesupport>, [">= 3"])
      s.add_dependency(%q<actionpack>, [">= 3"])
      s.add_dependency(%q<rspec>, ["~> 2"])
      s.add_dependency(%q<rcov>, [">= 0"])
    end
  else
    s.add_dependency(%q<activesupport>, [">= 3"])
    s.add_dependency(%q<actionpack>, [">= 3"])
    s.add_dependency(%q<rspec>, ["~> 2"])
    s.add_dependency(%q<rcov>, [">= 0"])
  end
end
